AgroTech/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import logout,login
from django.urls import path, include
from rest_framework import routers

from AgroTech import settings
from core import views
from catalog.api.viewsets import ProductViewSet, CategoryViewSet
from catalog.models import Product, Category

router = routers.DefaultRouter()
router.register(r'produtos', ProductViewSet, base_name=Product)
router.register(r'categorias', CategoryViewSet, base_name=Category)


urlpatterns = [
    path('', views.home, name='home'),
    path('vendas/', views.index, name='index'),
    path('contato/', views.contact, name='contact'),
    path('entrar/', login, {'template_name': 'login.html'}, name='login'),
    path('sair/', logout, {'next_page': 'home'}, name='logout'),
    path('registro/', views.register, name='register'),
    path('catalogo/', include('catalog.urls', namespace="catalog")),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('compras/', include('checkout.urls', namespace='checkout')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('servicos/',include('servico_profissional.urls', namespace='profissional_servicos')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static

from AgroTech import settings
from . import views

app_name="catalog"
urlpatterns=[

    path('',views.product_list, name='product_list'),
    url(r'^(?P<slug>[\w-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w-]+)/$', views.product, name='product'),
]

servico_profissional/urls.py
from django.urls import path
from . import views
app_name = 'servicoes_profissional'

urlpatterns = [
    path('', views.ViewServicos, name='listProfissional'),
    path('perfil/<int:id>/', views.ViewCurriculo, name='viewPerfil'),
]

servico_profissional/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class CategoryService(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)

    def get_absolute_url(self):
        return reverse('catalog:product',kwargs={'slug':self.slug})

    def __str__(self):
        return self.name

class experienciaProfissional(models.Model):
    local = models.CharField(max_length=150)
    periodo = models.CharField(max_length=150)
    descricao= models.TextField(blank=True,null=True)
    cargo = models.CharField(max_length=200)

    def __str__(self):
        return self.local
class PerfilProfissional(models.Model):
    #user = models.CharField(max_length=100, default=User.)
    nomeCompleto= models.CharField(max_length=100)
    foto = models.ImageField(upload_to='img_perfil')
    resumo = models.CharField(max_length=200)
    profissao = models.CharField(max_length=100)
    experiencias = models.ManyToManyField(experienciaProfissional)
    categoria = models.ForeignKey(CategoryService,on_delete=models.CASCADE)
    def __str__(self):
        return self.nomeCompleto

    def get_absolute_url(self):
        return reverse('catalog:product',kwargs={'slug':self.slug})

servico_profissional/views.py
from django.shortcuts import render
from .models import PerfilProfissional
# Create your views here.


def ViewCurriculo(request, id):
    perfil = PerfilProfissional.objects.get(pk=id)
    context = {
        'perfil':perfil
    }
    return  render(request, 'servico_profissional/Curriculo.html', context)

def ViewServicos(request):
    list = PerfilProfissional.objects.all()
    context ={
        'list': list
    }
    return render(request,'servico_profissional/Serviços.html', context)

servico_profissional/templates/servico_profissional/Curriculo.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Curriculo {{ perfil.nomeCompleto }} | AgroSale </title>

	    <link href="{% static 'assets/servicos/vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="{% static 'assets/servicos/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/servicos/vendor/devicons/css/devicons.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/servicos/vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'assets/servicos/css/resume.min.css'%}" rel="stylesheet">





</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
      <a class="navbar-brand js-scroll-trigger" href="{%  url 'profissional_servicos:listProfissional' %}">
        <span class="d-block d-lg-none">Start Bootstrap</span>
        <span class="d-none d-lg-block">
          <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'assets/servicos/img/profile.jpg'%} " alt="">
        </span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#experience">Experience</a>
          </li>
    </nav>
	<div class="container-fluid p-0">
      <section class="resume-section p-3 p-lg-5 d-flex d-column" id="about">
        <div class="my-auto">
          <h1 class="mb-0">{{ perfil.nomeCompleto }}
            <span class="text-primary">{{ perfil.nomeCompleto }}</span>
          </h1>
          <div class="subheading mb-5">3542 Berry Street · Cheyenne Wells, CO 80810 · (317) 585-8468 ·
            <a href="mailto:name@email.com">name@email.com</a>
          </div>
          <p class="mb-5">{{ perfil.resumo }}</p>
          <ul class="list-inline list-social-icons mb-0">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
        </div>
      </section>

      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="experience">
        <div class="my-auto">
          <h2 class="mb-5">Experience</h2>
            {% for experiencia in perfil.experiencias.all %}
          <div class="resume-item d-flex flex-column flex-md-row mb-5">
            <div class="resume-content mr-auto">
              <h3 class="mb-0">{{ experiencia.cargo }}</h3>
              <div class="subheading mb-3">{{ experiencia.local }}</div>
              <p>{{ experiencia.descricao }}</p>
            </div>
            <div class="resume-date text-md-right">
              <span class="text-primary">{{ experiencia.periodo }}</span>
            </div>
          </div>
            {% endfor %}

        </div>

      </section>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'assets/servicos/vendor/jquery/jquery.min.js'%} "></script>
    <script src="{% static 'assets/servicos/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'assets/servicos/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'assets/servicos/js/resume.min.js' %}"></script>

</body>
</html>

servico_profissional/templates/servico_profissional/Serviços.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Profissionais | AgroSale</title>
	<link href="{% static 'assets/servicos/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'assets/servicos/vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">
    <link href="{% static 'assets/servicos/css/4-col-portfolio.css'%} " rel="stylesheet">
	<style>
		body{
			margin: 0;
			padding: 0;
			background: url({% static 'assets/servicos/img/3.jpg' %}) no-repeat center fixed;
			background-size: cover;
			-vebkit-background-size:cover;
			-moz-background-size:cover
			-ms-background-size:cover;
			-o-background-size:cover;
		}
	</style>

</head>
<body>
    <div class="navbar-header">
          <a href="{% url 'home' %}" class="navbar-brand">Agro Sale</a>
          <button type="button" class="btn btn-primary">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
	<form action=" " method="post">
	  <center><h2 class="my-4">Qual Serviço você Procura ? </h2></center>
	  <div class="container">  
	    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" id="busca" name="q">
	    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">OK</button>
	  </div>
	</form>

	

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h2 class="my-4">Profissionais</h2>
        </div>
          {% for perfil in list %}
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="{{ perfil.foto.url }}" alt="">
           <div class="card-body">
              <h4 class="card-title">
                <a href="{% url 'profissional_servicos:viewPerfil' perfil.id %}">{{ perfil.profissao }}</a>
                <a href="#">{{ perfil.nomeCompleto }}</a>
              </h4>
              <p class="card-text">{{ perfil.resumo }}</p>
            </div>
        </div>
        {% endfor %}


      <ul class="pagination justify-content-center">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Anterior</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">1</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Proximo</span>
          </a>
        </li>
      </ul>
    </div>
    <footer class="py-5 bg-dark">
      <div class="container">
        <h6 class="m-0 text-center text-white">Copyright &copy; AgroSale 2018</h6>
      </div>
    </footer>
    <script src="{% static 'assets/servicos/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/servicos/vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
</body>
</html>