AgroTech/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import logout,login
from django.urls import path, include
from rest_framework import routers

from AgroTech import settings
from core import views
from catalog.api.viewsets import ProductViewSet, CategoryViewSet
from catalog.models import Product, Category

router = routers.DefaultRouter()
router.register(r'produtos', ProductViewSet, base_name=Product)
router.register(r'categorias', CategoryViewSet, base_name=Category)


urlpatterns = [
    path('', views.home, name='home'),
    path('vendas/', views.index, name='index'),
    path('contato/', views.contact, name='contact'),
    path('entrar/', login, {'template_name': 'login.html'}, name='login'),
    path('sair/', logout, {'next_page': 'home'}, name='logout'),
    path('registro/', views.register, name='register'),
    path('catalogo/', include('catalog.urls', namespace="catalog")),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('compras/', include('checkout.urls', namespace='checkout')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('servicos/',include('servico_profissional.urls', namespace='profissional_servicos')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static

from AgroTech import settings
from . import views

app_name="catalog"
urlpatterns=[

    path('',views.product_list, name='product_list'),
    url(r'^(?P<slug>[\w-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w-]+)/$', views.product, name='product'),
]

servico_profissional/urls.py
from django.urls import path
from . import views
app_name = 'servicoes_profissional'

urlpatterns = [
    path('', views.ViewServicos, name='listProfissional'),
    path('perfil/<int:id>/', views.ViewCurriculo, name='viewPerfil'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
# coding=utf-8

from django import forms
from django.core.mail import  send_mail
from django.conf import settings


class ContactForm(forms.Form):

    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())


    ####controlando como renderizar ####
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['class'] = 'form-control'


    ##metodo para enviar email###
    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        mensagem = self.cleaned_data['message']
        mensagem = 'Nome:{0}\nE-mail: {1}\nMensagem: {2}'.format(name, email, mensagem)
        send_mail('Contado do ecommerce', mensagem, settings.DEFAULT_FROM_EMAIL,
                  [settings.DEFAULT_FROM_EMAIL]
                  )

core/views.py
# coding=utf-8
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.mail import  send_mail
from django.urls import reverse_lazy

from .forms import ContactForm
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import View, TemplateView, CreateView
from django.contrib.auth import get_user_model

class HomeView(TemplateView):
    template_name = 'home.html'

home = HomeView.as_view()
class IndexView(TemplateView):


    template_name = 'index.html'


index = IndexView.as_view()

def contact(request):
    success = False
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success= True

    context = {
        'form': form,
        'success':success
    }
    return render(request, 'contact.html', context)

class RegisterView(CreateView):

    form_class = UserCreationForm
    template_name = 'register.html'
    model = User
    success_url = reverse_lazy('index')


register = RegisterView.as_view()

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Agro Sale{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120234715-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-120234715-1');
</script>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index' %}" class="navbar-brand">Agro Sale</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">

            <li>
              <a href="{% url 'catalog:product_list' %}">Produtos</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
				{% for category in categories %}
				<li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
				{% endfor %}
              </ul>
            </li>
			<li>
				<a href="{% url 'contact' %}">Contato</a>
			</li>
          </ul>
            <form class="navbar-form navbar-left" role="search" action="{% url 'catalog:product_list' %}">
	        <div class="form-group">
	          <input name="q" type="text" class="form-control" placeholder="Pesquisar..." />
	        </div>
	        </form>
          <ul class="nav navbar-nav navbar-right">
			  <li><a href="#">Carrinho</a></li>
			{% if user.is_authenticated %}
			<li><a href="{% url 'accounts:index' %}">Conta</a></li>
			<li><a href="{% url 'logout' %}">Sair</a></li>
			{% else %}
			<li><a href="{% url 'login' %}">Entrar</a></li>
			<li><a href="{% url 'accounts:register' %}">Registro</a></li>
			{% endif %}
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
		{% block messages %}
		{% for message in messages %}
		<div class="alert alert-{{ message.tags }}">
			{{ message }}
		</div>
		{% endfor %}
		{% endblock %}
        {% block container %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="">Início</a></li>
			      <li><a href="">Produtos</a></li>
			      <li><a href="">Contato</a></li>
			      <li><a href="">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>


</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Fale conosco</h1>
    {% if success %}
        <div class="alert alert-success">
        Mensagem enviada com sucesso
        </div>
    {% endif %}
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                  {{ field }}
                  {% comment %}
                    {% render_field field class='form-control' %}
                {% endcomment %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

core/templates/home.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Home - AgroSale</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  
    <link rel="stylesheet" href="{% static 'assets/home/font-awesome-4.5.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/home/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/home/css/hero-slider-style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/home/css/templatemo-style.css' %}">


</head>

    
    <body>

        <section class="cd-hero">


            <ul class="cd-hero-slider autoplay">

                <li class="selected">
                    <center>
                        <br>
                        <img src="{% static 'assets/home/img/logo.png' %}">
                    
                    <br>
                </center>
                    <div class="cd-half-width">
                        <div class="tm-slide-content-div pull-xs-right">
                            <form action="{% url 'profissional_servicos:listProfissional' %}" id="search-form">
                                <i class="fa fa-group tm-slide-icon"></i>
                                <h2 class="text-uppercase">Buscando profissionais?</h2>
                                <p class="m-b-mid">Você busca um profissional para qual serviço?</p>
                                <div class="form-group">
                                    <input name="search" type="text" class="form-control center-block tm-max-w-400" id="input1" placeholder="Digite o que você procura...">
                              </div>                                
                                <button type="submit" class="cd-btn">Pesquisar</button>
                                
                            </form>                            
                        </div>                        
                    </div> <!-- .cd-full-width -->




                    <div class="cd-half-width">
                        <div class="tm-slide-content-div">
                            <form role="search" action="{% url 'catalog:product_list' %}">
                                <i class="fa fa-leaf tm-slide-icon"></i>
                                <h2 class="text-uppercase">Buscando insumos?</h2>
                                <p class="m-b-mid">Qual o produto que você precisa?</p>
                                <div class="form-group">
                                    <input name="q" type="text" class="form-control" placeholder="Digite o que você procura...">
                              </div>                                
                                <button type="submit" class="cd-btn">Pesquisar</button>
                                
                            </form>                            
                        </div>                        
                    </div>
                </li>

            </ul> <!-- .cd-hero-slider -->
<br>
            <ul class="row" align="center">
                {% for category in categories %}
                <a class="nav-link " style="margin: 0px 8px 0px 8px" href="{{ category.get_absolute_url }}"><b>{{ category }}</b></a>

               {% endfor %}

            </ul>


        </section> <!-- .cd-hero -->

        
        <script src="{% static 'assets/home/js/jquery-1.11.3.min.js' %}"></script>
        <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script>
        <script src="{% static 'assets/home/js/bootstrap.min.js' %}"></script>
              
       
</body>
</html>

core/templates/index.html
{% extends "base.html" %}
{% block container %}
    <div class="jumbotron page-header">
		  <h1>Agro - Sale </h1>
		  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
		  <p><a class="btn btn-primary">Saiba mais</a></p>
		</div>
{% endblock %}

core/templates/login.html
{% extends "base.html" %}

{% block title %}
    Entrar | {{ block.super }}
{% endblock %}
{% load widget_tweaks%}

{% block container %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="page-header">
                    <h1>Entrar</h1>
                </div>
                <form class="form-horizontal" method="post">
                    {% csrf_token %}
                {% for error in form.non_field_errors %}
                    <div class="alert-danger">
                    {{ error }}
                    </div>
                {% endfor %}
                    <fieldset>
                        <div class="form-group" {% if form.username.errors %} has-error {% endif %}>
                          <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                          <div class="col-md-9">
                            {% render_field form.username class="form-control" %}
                              {% for error in form.username.errors %}
                              <span class="help-block">{{ error }}</span>
                              {% endfor %}
                          </div>
                        </div>
                        <div class="form-group" {% if form.password.errors %} has-error {% endif %}>
                          <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                          <div class="col-md-9">
                            {% render_field form.password class="form-control" %}
                              {% for error in field.password.errors %}
                              <span class="help-block">{{ error }}</span>
                              {% endfor %}
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Enviar</button>
                          </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
{% endblock %}

core/templates/pagination.html
<div class="row">
    <div class="col-md-12">
        <nav>
            <ul class="pagination">
                {% for page in paginator.page_range %}
                <li {% if page_obj.number == page %} class="active" {% endif %}><a href="?page={{ page }}">{{ page }}</a></li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</div>

core/templates/register.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Registro | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Registro</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                  <div class="col-md-9">
                   {% comment %} {% render_field field class="form-control" %} {% endcomment %}
                        {{ field }}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Registrar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}